// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZGTzur6GtDs9oUjj3vTiHHmljWNh1GGs',
    appId: '1:239614880103:web:bee184158a7c04bf3a27c2',
    messagingSenderId: '239614880103',
    projectId: 'flash-chat-2d87f',
    authDomain: 'flash-chat-2d87f.firebaseapp.com',
    storageBucket: 'flash-chat-2d87f.appspot.com',
    measurementId: 'G-C64JS03L6P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNfhV-NAKvkWnloWyJzOtgy6287gHMXy8',
    appId: '1:239614880103:android:e9f5a1d9d47b03143a27c2',
    messagingSenderId: '239614880103',
    projectId: 'flash-chat-2d87f',
    storageBucket: 'flash-chat-2d87f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXgw_-r0s6fsWWd4R6Kw52XYu0XJPWHQA',
    appId: '1:239614880103:ios:edb2ca048c30413f3a27c2',
    messagingSenderId: '239614880103',
    projectId: 'flash-chat-2d87f',
    storageBucket: 'flash-chat-2d87f.appspot.com',
    iosBundleId: 'com.example.flashChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXgw_-r0s6fsWWd4R6Kw52XYu0XJPWHQA',
    appId: '1:239614880103:ios:99460202460f802c3a27c2',
    messagingSenderId: '239614880103',
    projectId: 'flash-chat-2d87f',
    storageBucket: 'flash-chat-2d87f.appspot.com',
    iosBundleId: 'com.example.flashChat.RunnerTests',
  );
}
